In [ ]:
# QKV
# the formula:
import numpy as np

# head = 8, d_model = 512, n=4
# down to head=2, d_model=8, n = 4, so k=4
# W(Q)= (n, k) = (4,4) ; so as K an V, then h=2, which means in the end we will have 
# b =  2, d_model=8, and n=4 (tokens)

h = 2
d_model  = 8
k = d_model // h
n = 4 # number of tokens

weight_shape = (n, k)

w_q = np.random.randint(1,10, size=weight_shape)
w_k = np.random.randint(1,10, size=weight_shape)
w_v = np.random.randint(1,10, size=weight_shape)

print(w_q)
print(w_k)
print(w_v)



[[9 9 6 7]
 [4 1 1 1]
 [3 1 1 4]
 [3 2 3 4]]
[[1 2 5 3]
 [1 6 8 3]
 [6 4 9 1]
 [1 5 8 4]]
[[3 9 2 9]
 [2 2 4 6]
 [6 2 1 6]
 [4 4 9 8]]


In [14]:
input_shape = (h, n, d_model)

w = np.random.randint(1,10, size=input_shape)

print(w)

[[[5 1 3 1 3 5 2 3]
  [1 5 2 3 8 5 9 6]
  [3 4 1 6 3 7 1 3]
  [4 5 7 7 3 5 3 2]]

 [[7 6 7 4 2 4 6 4]
  [9 7 7 1 2 3 6 6]
  [1 9 2 2 6 7 4 9]
  [1 1 5 7 9 7 1 8]]]
